# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1ee27d4a07d8197c31a5d5c5c5f7523b8e0a4ba56e3d8034edbd62fd14b15573f7ed78af8b5950a72308104facd8360e7b63432804c094f1f62b80589e67c63

test:
  secret_key_base: ee08ea58d0520496813fe84809e6c2ab3e7432123a6a06cab91d9b05444810e34359e49acc8dc245ee2696d648c7fef64ec2060b3bff75de3b10b7c39e11a12d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
